-- MySQL Script generated by MySQL Workbench
-- 06/08/15 15:32:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infotaxes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infotaxes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infotaxes` DEFAULT CHARACTER SET utf8 ;
USE `infotaxes` ;

-- -----------------------------------------------------
-- Table `infotaxes`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`servicio` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(75) NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(95) NULL,
  `descripcion` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`territorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`territorio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(95) NULL,
  `tipo` VARCHAR(1) NULL,
  `territorio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_territorio_territorio1_idx` (`territorio_id` ASC),
  CONSTRAINT `fk_territorio_territorio1`
    FOREIGN KEY (`territorio_id`)
    REFERENCES `infotaxes`.`territorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`sucursal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(95) NOT NULL,
  `descripcion` VARCHAR(128) NULL,
  `direccion` VARCHAR(95) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `correo` VARCHAR(45) NULL,
  `tipo_id` INT NOT NULL,
  `territorio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursal_tipo1_idx` (`tipo_id` ASC),
  INDEX `fk_sucursal_territorio1_idx` (`territorio_id` ASC),
  CONSTRAINT `fk_sucursal_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `infotaxes`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal_territorio1`
    FOREIGN KEY (`territorio_id`)
    REFERENCES `infotaxes`.`territorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`horasuse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`horasuse` (
  `sucursal_id` INT NOT NULL,
  `servicio_id` INT NOT NULL,
  `horaIn` VARCHAR(45) NOT NULL,
  `horafin` VARCHAR(45) NOT NULL,
  `decripcion` VARCHAR(120) NULL DEFAULT '.',
  INDEX `fk_horasuse_sucursal1_idx` (`sucursal_id` ASC),
  INDEX `fk_horasuse_servicio1_idx` (`servicio_id` ASC),
  CONSTRAINT `fk_horasuse_sucursal1`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `infotaxes`.`sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horasuse_servicio1`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `infotaxes`.`servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `apellido` VARCHAR(65) NOT NULL,
  `correo` VARCHAR(65) NULL,
  `rol` VARCHAR(45) NOT NULL,
  `territorio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_territorio1_idx` (`territorio_id` ASC),
  CONSTRAINT `fk_usuario_territorio1`
    FOREIGN KEY (`territorio_id`)
    REFERENCES `infotaxes`.`territorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
