-- MySQL Script generated by MySQL Workbench
-- 06/08/15 17:16:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infotaxes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infotaxes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infotaxes` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema wanapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wanapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wanapp` DEFAULT CHARACTER SET utf8 ;
USE `infotaxes` ;

-- -----------------------------------------------------
-- Table `infotaxes`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`servicio` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(75) NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(95) NULL,
  `descripcion` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`territorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`territorio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(95) NULL,
  `tipo` VARCHAR(1) NULL,
  `territorio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_territorio_territorio1_idx` (`territorio_id` ASC),
  CONSTRAINT `fk_territorio_territorio1`
    FOREIGN KEY (`territorio_id`)
    REFERENCES `infotaxes`.`territorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`sucursal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(95) NOT NULL,
  `descripcion` VARCHAR(128) NULL,
  `direccion` VARCHAR(95) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `correo` VARCHAR(45) NULL,
  `tipo_id` INT NOT NULL,
  `territorio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursal_tipo1_idx` (`tipo_id` ASC),
  INDEX `fk_sucursal_territorio1_idx` (`territorio_id` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  CONSTRAINT `fk_sucursal_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `infotaxes`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal_territorio1`
    FOREIGN KEY (`territorio_id`)
    REFERENCES `infotaxes`.`territorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`horasuse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`horasuse` (
  `idhorasuse` INT NOT NULL AUTO_INCREMENT,
  `sucursal_id` INT NOT NULL,
  `servicio_id` INT NOT NULL,
  `horaIn` VARCHAR(45) NOT NULL,
  `horafin` VARCHAR(45) NOT NULL,
  `decripcion` VARCHAR(120) NULL DEFAULT '.',
  INDEX `fk_horasuse_sucursal1_idx` (`sucursal_id` ASC),
  INDEX `fk_horasuse_servicio1_idx` (`servicio_id` ASC),
  PRIMARY KEY (`idhorasuse`),
  CONSTRAINT `fk_horasuse_sucursal1`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `infotaxes`.`sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horasuse_servicio1`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `infotaxes`.`servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `apellido` VARCHAR(65) NOT NULL,
  `correo` VARCHAR(65) NULL,
  `rol` VARCHAR(45) NOT NULL,
  `territorio_id` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(128) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_territorio1_idx` (`territorio_id` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC),
  CONSTRAINT `fk_usuario_territorio1`
    FOREIGN KEY (`territorio_id`)
    REFERENCES `infotaxes`.`territorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infotaxes`.`estadistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotaxes`.`estadistica` (
  `idestadistica` INT NOT NULL AUTO_INCREMENT,
  `valor` INT(1) NOT NULL DEFAULT 1,
  `comentario` TEXT(4000) NULL,
  `isaprobado` TINYINT(1) NOT NULL DEFAULT 0,
  `sucursal_id` INT NOT NULL,
  `servicio_id` INT NULL,
  PRIMARY KEY (`idestadistica`),
  INDEX `fk_estadistica_sucursal1_idx` (`sucursal_id` ASC),
  INDEX `fk_estadistica_servicio1_idx` (`servicio_id` ASC),
  CONSTRAINT `fk_estadistica_sucursal1`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `infotaxes`.`sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estadistica_servicio1`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `infotaxes`.`servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `wanapp` ;

-- -----------------------------------------------------
-- Table `wanapp`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wanapp`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wanapp`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wanapp`.`zona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zona_pais_idx` (`pais_id` ASC),
  CONSTRAINT `fk_zona_pais`
    FOREIGN KEY (`pais_id`)
    REFERENCES `wanapp`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wanapp`.`suscriptor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wanapp`.`suscriptor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `apellido` VARCHAR(75) NOT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `zona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suscriptor_zona1_idx` (`zona_id` ASC),
  CONSTRAINT `fk_suscriptor_zona1`
    FOREIGN KEY (`zona_id`)
    REFERENCES `wanapp`.`zona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wanapp`.`notaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wanapp`.`notaria` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(65) NULL DEFAULT NULL,
  `descripcion` VARCHAR(120) NULL DEFAULT NULL,
  `direccion` VARCHAR(85) NULL DEFAULT NULL,
  `tel` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wanapp`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wanapp`.`servicio` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(75) NULL DEFAULT NULL,
  `notaria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicio_notaria1_idx` (`notaria_id` ASC),
  CONSTRAINT `fk_servicio_notaria1`
    FOREIGN KEY (`notaria_id`)
    REFERENCES `wanapp`.`notaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wanapp`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wanapp`.`horario` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `hora` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `notaria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horario_notaria1_idx` (`notaria_id` ASC),
  CONSTRAINT `fk_horario_notaria1`
    FOREIGN KEY (`notaria_id`)
    REFERENCES `wanapp`.`notaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wanapp`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wanapp`.`favorito` (
  `idfavorito` INT NOT NULL,
  `suscriptor_id` INT NOT NULL,
  `notaria_id` INT NOT NULL,
  PRIMARY KEY (`idfavorito`),
  INDEX `fk_favorito_suscriptor1_idx` (`suscriptor_id` ASC),
  INDEX `fk_favorito_notaria1_idx` (`notaria_id` ASC),
  CONSTRAINT `fk_favorito_suscriptor1`
    FOREIGN KEY (`suscriptor_id`)
    REFERENCES `wanapp`.`suscriptor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_notaria1`
    FOREIGN KEY (`notaria_id`)
    REFERENCES `wanapp`.`notaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
