package com.infotaxes.pojos;
// Generated 8/06/2015 05:19:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Estadistica generated by hbm2java
 */
@Entity
@Table(name="estadistica"
    ,catalog="infotaxes"
)
public class Estadistica  implements java.io.Serializable {


     private Integer idestadistica;
     private Servicio servicio;
     private Sucursal sucursal;
     private int valor;
     private String comentario;
     private boolean isaprobado;

    public Estadistica() {
    }

	
    public Estadistica(Sucursal sucursal, int valor, boolean isaprobado) {
        this.sucursal = sucursal;
        this.valor = valor;
        this.isaprobado = isaprobado;
    }
    public Estadistica(Servicio servicio, Sucursal sucursal, int valor, String comentario, boolean isaprobado) {
       this.servicio = servicio;
       this.sucursal = sucursal;
       this.valor = valor;
       this.comentario = comentario;
       this.isaprobado = isaprobado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idestadistica", unique=true, nullable=false)
    public Integer getIdestadistica() {
        return this.idestadistica;
    }
    
    public void setIdestadistica(Integer idestadistica) {
        this.idestadistica = idestadistica;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="servicio_id")
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sucursal_id", nullable=false)
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }

    
    @Column(name="valor", nullable=false)
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }

    
    @Column(name="comentario", length=65535)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="isaprobado", nullable=false)
    public boolean isIsaprobado() {
        return this.isaprobado;
    }
    
    public void setIsaprobado(boolean isaprobado) {
        this.isaprobado = isaprobado;
    }




}


