package com.infotaxes.pojos;
// Generated 8/06/2015 05:19:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="servicio"
    ,catalog="infotaxes"
)
public class Servicio  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private double valor;
     private Set horasuses = new HashSet(0);
     private Set estadisticas = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(double valor) {
        this.valor = valor;
    }
    public Servicio(String descripcion, double valor, Set horasuses, Set estadisticas) {
       this.descripcion = descripcion;
       this.valor = valor;
       this.horasuses = horasuses;
       this.estadisticas = estadisticas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=75)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="valor", nullable=false, precision=22, scale=0)
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getHorasuses() {
        return this.horasuses;
    }
    
    public void setHorasuses(Set horasuses) {
        this.horasuses = horasuses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set getEstadisticas() {
        return this.estadisticas;
    }
    
    public void setEstadisticas(Set estadisticas) {
        this.estadisticas = estadisticas;
    }




}


