package com.infotaxes.pojos;
// Generated 8/06/2015 03:52:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="sucursal"
    ,catalog="infotaxes"
    , uniqueConstraints = @UniqueConstraint(columnNames="correo") 
)
public class Sucursal  implements java.io.Serializable {


     private Integer id;
     private Territorio territorio;
     private Tipo tipo;
     private String nombre;
     private String descripcion;
     private String direccion;
     private String telefono;
     private String correo;
     private Set horasuses = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(Territorio territorio, Tipo tipo, String nombre, String direccion) {
        this.territorio = territorio;
        this.tipo = tipo;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Sucursal(Territorio territorio, Tipo tipo, String nombre, String descripcion, String direccion, String telefono, String correo, Set horasuses) {
       this.territorio = territorio;
       this.tipo = tipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.horasuses = horasuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="territorio_id", nullable=false)
    public Territorio getTerritorio() {
        return this.territorio;
    }
    
    public void setTerritorio(Territorio territorio) {
        this.territorio = territorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_id", nullable=false)
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="nombre", nullable=false, length=95)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=128)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="direccion", nullable=false, length=95)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="correo", unique=true, length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursal")
    public Set getHorasuses() {
        return this.horasuses;
    }
    
    public void setHorasuses(Set horasuses) {
        this.horasuses = horasuses;
    }




}


