package com.infotaxes.pojos;
// Generated 8/06/2015 03:52:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="infotaxes"
    , uniqueConstraints = @UniqueConstraint(columnNames="correo") 
)
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private Territorio territorio;
     private String nombre;
     private String apellido;
     private String correo;
     private String rol;
     private String login;
     private String clave;
     private Integer estado;

    public Usuario() {
    }

    public Usuario(Territorio territorio, String nombre, String apellido, String correo, String rol, String login, String clave, Integer estado) {
        this.territorio = territorio;
        this.nombre = nombre;
        this.apellido = apellido;
        this.correo = correo;
        this.rol = rol;
        this.login = login;
        this.clave = clave;
        this.estado = estado;
    }

    public Usuario(Territorio territorio, String nombre, String apellido, String rol, String login, String clave, Integer estado) {
        this.territorio = territorio;
        this.nombre = nombre;
        this.apellido = apellido;
        this.rol = rol;
        this.login = login;
        this.clave = clave;
        this.estado = estado;
    }	
  
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="territorio_id", nullable=false)
    public Territorio getTerritorio() {
        return this.territorio;
    }
    
    public void setTerritorio(Territorio territorio) {
        this.territorio = territorio;
    }

    
    @Column(name="nombre", nullable=false, length=75)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=65)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="correo", unique=true, length=65)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="rol", nullable=false, length=45)
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }

}


